# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [14]:
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [91]:
arr = np.arange(10,50)
arr.shape

(40,)

5. Print the type of the previous array in question 3

In [92]:
arr = np.arange(10,50)
arr.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [8]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [93]:
arr = np.arange(10,50)
arr.ndim

1

8. Create a boolean array with all the True values

In [94]:
bool_arr = np.ones(10, dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array

In [50]:
x = np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

10. Create a three dimensional array



In [18]:
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [95]:
arr = np.arange(10,50)
np.flip(arr)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [96]:
x = (np.arange(10) == 4).astype(int)
print(x)

[0 0 0 0 1 0 0 0 0 0]


13. Create a 3x3 identity matrix

In [97]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [98]:
arr = np.array([1, 2, 3, 4, 5])
y = arr.astype(float)
print(y)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [99]:
arr1 = np.array([[1., 2., 3.],
                        [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                       [7., 2., 12.]])

new_arr = arr1 * arr2

print(new_arr)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [39]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
            [7., 2., 12.]])
comparison = arr1 == arr2
equal_arrays = comparison.all() 
  
print(equal_arrays) 

False

17. Extract all odd numbers from arr with values(0-9)

In [103]:
arr = np.arange(10)
arr = np.where(arr % 2 == 0)
print(arr)

(array([0, 2, 4, 6, 8], dtype=int64),)


18. Replace all odd numbers to -1 from previous array

In [106]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print(arr)    

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [36]:
arr = np.arange(10)
arr[4:8] = 12
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [63]:
arr = np.ones((6, 6))
print(arr)
arr[1:-1 , 1:-1] = 0
print("\n The new Array is: ", "\n\n", arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

 The new Array is:  

 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [107]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1, 1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [108]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0, :] = 64
print(arr3d)


[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [112]:
x = np.arange(10).reshape(2,5)
y = (x[:1, :])
print(y)

[[0 1 2 3 4]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [113]:
x = np.arange(10).reshape(2,5)
y = x[1, 1]
print(y)

6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [114]:
x = np.arange(10).reshape(2,5)
y = x[:2, 2]
print(y)

[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [120]:
y = np.random.random((10, 10))
print("The 10x10 Array is: ", "\n\n", y)
print("\n The Minimum value is: ", y.min())
print("\n The Maximum value is; ", y.max())

The 10x10 Array is:  

 [[3.30521154e-01 3.62129564e-01 6.43857791e-03 5.49564452e-01
  8.50959925e-01 8.29871094e-01 4.27037204e-01 3.19184104e-02
  6.96155243e-01 4.91597183e-01]
 [5.21940686e-02 7.27855560e-01 2.24686962e-02 6.86426098e-01
  8.92061716e-01 1.92267488e-01 4.97143490e-01 8.62438465e-01
  9.10248390e-01 6.36499890e-01]
 [1.81547644e-01 9.51698124e-01 6.96562566e-01 2.26924854e-01
  7.03270845e-01 6.11204179e-01 2.97312043e-01 1.73030506e-01
  8.68586022e-01 3.25721211e-02]
 [8.70363013e-04 9.38887712e-01 9.32528853e-01 6.45579141e-01
  9.47683167e-01 6.91551197e-01 9.54983310e-01 8.05896878e-01
  7.79992932e-01 8.95280165e-01]
 [3.61322043e-01 3.66235674e-01 4.03086331e-04 2.03188334e-01
  4.90767844e-01 5.08397959e-01 2.97735489e-01 4.55898510e-02
  3.76585588e-01 3.19823478e-02]
 [4.62198173e-01 7.59106802e-01 3.11639545e-01 8.77474122e-01
  4.32281693e-01 1.41437294e-01 3.04726747e-01 7.42386422e-01
  3.45523521e-01 5.87211178e-01]
 [6.67269894e-01 2.51395586e-01 8.

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [121]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [122]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [123]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data




array([[ 1.16492582,  0.72759079,  0.67756355,  0.07844245],
       [-0.56659006,  1.0575054 , -0.77571361,  0.63396616],
       [ 0.7270017 , -0.83394077, -0.12930862,  0.84885206],
       [ 0.25275226, -0.12025084,  1.4947961 ,  2.19384237],
       [ 0.50431686, -0.21048108, -0.88002338, -0.24733123],
       [ 0.53366757, -1.11989516,  0.03416035, -0.03914274],
       [-0.68032294,  0.45959324,  0.36956212,  0.76352841]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [44]:
arr = np.random.uniform(1, 15, size=(5, 3))
print(arr)

[[13.56401347  3.77033455 12.20598092]
 [ 3.67430829  7.59339539 13.3014703 ]
 [11.69998859 12.92044477  7.75611508]
 [12.29799456 12.09016407 10.26967284]
 [ 4.56140935 12.66758875  2.33194273]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [45]:
arr = np.random.uniform(1, 16, size=(2,2,4))
print(arr)

[[[12.31022954 14.41776652 14.42889728  4.5123712 ]
  [13.54224659  1.19521506  1.12483599  3.32832038]]

 [[13.46305921  6.8845998   2.27807248  8.26213463]
  [ 4.58626452 15.6101801  13.94082838  1.89129039]]]


33. Swap axes of the array you created in Question 32

In [127]:
arr = np.random.uniform(1, 16, size=(2, 2, 4))
print("The Array is: ", "\n\n", arr)
print("\n The Swapped Array is: ", "\n\n", np.swapaxes(arr, 0, 2))

The Array is:  

 [[[ 4.25902685 14.75675445 12.83201241  7.98118117]
  [12.16393402  1.76897987 15.25002372 15.15817881]]

 [[ 7.90951431 12.88209025  8.06738714 10.51703053]
  [15.07239735  9.60185836 13.25473217 13.22531035]]]

 The Swapped Array is:  

 [[[ 4.25902685  7.90951431]
  [12.16393402 15.07239735]]

 [[14.75675445 12.88209025]
  [ 1.76897987  9.60185836]]

 [[12.83201241  8.06738714]
  [15.25002372 13.25473217]]

 [[ 7.98118117 10.51703053]
  [15.15817881 13.22531035]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [59]:
x = np.random.random(10)
print(x)
y = np.sqrt(x)
print(y)
z = np.where(y > 0.5, y, 0)
print(z)

[0.39417854 0.40916809 0.88288393 0.00119836 0.69722075 0.37904451
 0.86331798 0.69445124 0.04662894 0.85324381]
[0.62783639 0.63966249 0.93961904 0.03461734 0.83499745 0.6156659
 0.92914906 0.83333741 0.21593736 0.92371198]
[0.62783639 0.63966249 0.93961904 0.         0.83499745 0.6156659
 0.92914906 0.83333741 0.         0.92371198]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [63]:
x = np.random.random(12)
print(x)
y = np.random.random(12)
print(y)
z = np.maximum(x, y)
print(z)

[0.14402584 0.13061056 0.57464212 0.42093584 0.24803344 0.98242947
 0.26587389 0.12873683 0.93264491 0.88999445 0.84288509 0.30726651]
[0.14661401 0.43718282 0.3883502  0.95276    0.09105272 0.60106184
 0.67203458 0.38746947 0.80045588 0.21668228 0.20607305 0.32499876]
[0.14661401 0.43718282 0.57464212 0.95276    0.24803344 0.98242947
 0.67203458 0.38746947 0.93264491 0.88999445 0.84288509 0.32499876]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [79]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a, b)
print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [128]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[: , 1]  = newColumn
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [87]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x, y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [90]:
x = np.random.random(20)
print(x.cumsum())

[0.19688481 0.71187491 1.69049366 2.02469703 2.08612861 2.58888455
 3.13615018 3.7471516  4.26034344 5.22993291 5.5802892  6.23109558
 6.54510356 7.4690795  7.96202055 8.50730614 8.50899015 9.09578864
 9.35840787 9.83511784]
