# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
import numpy as np

In [8]:
a = np.arange(0, 10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [33]:
a = np.arange(0, 10).reshape(2, 5)
b = np.ones(10).astype(np.int8).reshape(2, 5)
c = np.vstack((a, b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [34]:
a = np.arange(0, 10).reshape(2, 5)
b = np.ones(10).astype(np.int8).reshape(2, 5)
c = np.hstack((a, b))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [37]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8 ,9]])
b = a.flatten()
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [41]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8 ,9], [10, 11, 12, 13, 14]])
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [44]:
a = np.arange(0, 15)
b = a.reshape(5, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [54]:
a = np.random.random((5, 5))
print(a)
b = np.square(a)
print("\n\n Square of Array is: ", "\n\n", b)

[[0.99617589 0.53222294 0.68011597 0.37517518 0.60648977]
 [0.77583442 0.78340914 0.02563367 0.84417114 0.01535641]
 [0.88926586 0.01179341 0.6250033  0.17433486 0.13610698]
 [0.42090403 0.24348119 0.0449178  0.2727914  0.95328811]
 [0.66997334 0.76812003 0.41643855 0.33098005 0.66950529]]


 Square of Array is:  

 [[9.92366400e-01 2.83261257e-01 4.62557739e-01 1.40756417e-01
  3.67829842e-01]
 [6.01919047e-01 6.13729877e-01 6.57085026e-04 7.12624920e-01
  2.35819210e-04]
 [7.90793772e-01 1.39084420e-04 3.90629121e-01 3.03926427e-02
  1.85251097e-02]
 [1.77160201e-01 5.92830906e-02 2.01760865e-03 7.44151471e-02
  9.08758212e-01]
 [4.48864283e-01 5.90008386e-01 1.73421066e-01 1.09547795e-01
  4.48237335e-01]]


## Question:8

### Create 5x6 an array and find the mean?

In [55]:
a = np.random.random((5, 6))
print(a)
b = np.mean(a)
print("\n\n Mean of Array is: ", b)

[[0.91728371 0.12388416 0.74100098 0.6009182  0.25665133 0.45861038]
 [0.1114287  0.72037227 0.22643964 0.5284458  0.32665231 0.97962787]
 [0.51184219 0.21373015 0.92213573 0.21455058 0.21681476 0.18298332]
 [0.18913978 0.35719617 0.28156585 0.05689276 0.77344993 0.2981779 ]
 [0.14682788 0.22806353 0.83919927 0.01071413 0.77193056 0.86597672]]


 Mean of Array is:  0.43575021869494496


## Question:9

### Find the standard deviation of the previous array in Q8?

In [56]:
a = np.random.random((5, 6))
print(a)
b = np.std(a)
print("\n\n Standard Deviation of Array is: ", b)

[[0.13988907 0.94754819 0.6330475  0.48568654 0.36094588 0.2524641 ]
 [0.75554741 0.29813333 0.08811069 0.54956918 0.76051881 0.75228505]
 [0.92832167 0.52229681 0.35522228 0.55583308 0.51755712 0.7503229 ]
 [0.66565761 0.71614645 0.53724172 0.46319413 0.59175435 0.33818479]
 [0.34645196 0.9072304  0.48366338 0.31722239 0.10905624 0.13466465]]


 Standard Deviation of Array is:  0.23998366999748788


## Question:10

### Find the median of the previous array in Q8?

In [57]:
a = np.random.random((5, 6))
print(a)
b = np.median(a)
print("\n\n Median of Array is: ", b)

[[0.94726024 0.45767025 0.29814954 0.70991723 0.34075971 0.47235633]
 [0.53994613 0.45152059 0.7647852  0.44172524 0.32300843 0.6178877 ]
 [0.24588054 0.8497584  0.55111269 0.46073692 0.28312943 0.29289731]
 [0.91526737 0.56429567 0.81699209 0.59441325 0.63441913 0.33950297]
 [0.44370901 0.30083216 0.76013742 0.08710564 0.2455495  0.88605202]]


 Median of Array is:  0.4665466237247851


## Question:11

### Find the transpose of the previous array in Q8?

In [61]:
a = np.random.random((5, 6))
print(a)
b = np.transpose(a)
print("\n\n Transpose of Array is: ", "\n\n", b)

[[0.00934772 0.45373626 0.5249114  0.45140394 0.7959183  0.96264189]
 [0.59161545 0.92587904 0.4226859  0.46061216 0.69799169 0.16582174]
 [0.04172646 0.48105454 0.65960034 0.89543223 0.00523861 0.53664552]
 [0.33395311 0.55300712 0.72637524 0.18314565 0.78214135 0.6997979 ]
 [0.13071698 0.28948293 0.78589415 0.36739894 0.08561363 0.02054757]]


 Transpose of Array is:  

 [[0.00934772 0.59161545 0.04172646 0.33395311 0.13071698]
 [0.45373626 0.92587904 0.48105454 0.55300712 0.28948293]
 [0.5249114  0.4226859  0.65960034 0.72637524 0.78589415]
 [0.45140394 0.46061216 0.89543223 0.18314565 0.36739894]
 [0.7959183  0.69799169 0.00523861 0.78214135 0.08561363]
 [0.96264189 0.16582174 0.53664552 0.6997979  0.02054757]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [60]:
a = np.random.random((4, 4))
print(a)
b = np.diagonal(a)
print("\n\n Sum of Diagonal Elements is: ", "\n\n", b)

[[0.68865185 0.49391836 0.02461879 0.27646113]
 [0.01329928 0.19999641 0.39481069 0.10461544]
 [0.13270735 0.90685338 0.25963981 0.17628298]
 [0.83545936 0.81168673 0.88348215 0.38487458]]


 Sum of Diagonal Elements is:  

 [0.68865185 0.19999641 0.25963981 0.38487458]


## Question:13

### Find the determinant of the previous array in Q12?

In [66]:
a = np.random.random((4, 4))
print(a)
b = np.linalg.det(a)
print("\n\n Determinent of Array is: ", "\n\n", b)

[[0.31857474 0.28223371 0.37783372 0.5196898 ]
 [0.87869149 0.31958675 0.60959912 0.50626064]
 [0.10326372 0.41864141 0.69830386 0.95395328]
 [0.48167295 0.79115526 0.22965503 0.33144334]]


 Determinent of Array is:  

 0.0340823789435149


## Question:14

### Find the 5th and 95th percentile of an array?

In [71]:
a = np.arange(3, 20)
print(a)
b = np.percentile(a, 5)
print("\n\n 5th Percentile of Array is: ", "\n\n", b)
c = np.percentile(a, 95)
print("\n\n 95th Percentile of Array is: ", "\n\n", c)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


 5th Percentile of Array is:  

 3.8


 95th Percentile of Array is:  

 18.2


## Question:15

### How to find if a given array has any null values?

In [77]:
a = np.arange(0, 20).reshape(5, 4)
print(a)
print("\n\n Looking for Null Values: \n\n", np.isnan(a))

b = np.arange(15).reshape(5, 3)
print("\n\n", b)
print("\n\n Looking for Null Values: \n\n", np.isnan(b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


 Looking for Null Values: 

 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


 Looking for Null Values: 

 [[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]
